### ISSUE TITLE
Removal due to ASSIGNMENT

### ISSUE THREAD

**Issue by agrieco** [beancount/johnny#14]
It looks like there isn't any condition in the current processing (at least for Think or Swim) for assignment of an options contract.  Here is an example.

```
INFO    : Operation: 'read_config'                                    Time:      1 ms
Traceback (most recent call last):
  File "/home/agrieco/johnny/bin/johnny-import", line 160, in <module>
    import_()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/agrieco/johnny/bin/johnny-import", line 119, in import_
    transactions = ImportTransactions(config, force)
  File "/home/agrieco/johnny/bin/johnny-import", line 48, in ImportTransactions
    logtables = discovery.ImportConfiguredInputs(
  File "/home/agrieco/johnny/johnny/base/discovery.py", line 122, in ImportConfiguredInputs
    table = module.Import(account.source, config, logtype)
  File "/home/agrieco/johnny/johnny/sources/thinkorswim_csv/transactions.py", line 1134, in Import
    return ImportAll(source, config)[logtype]
  File "/home/agrieco/johnny/johnny/sources/thinkorswim_csv/transactions.py", line 1119, in ImportAll
    transactions, other = GetTransactions(filename)
  File "/home/agrieco/johnny/johnny/sources/thinkorswim_csv/transactions.py", line 980, in GetTransactions
    equities_trade, cashbal_nontrade = SplitCashBalance(cashbal, trade_hist)
  File "/home/agrieco/johnny/johnny/sources/thinkorswim_csv/transactions.py", line 94, in SplitCashBalance
    if joined.nrows() != 0:
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/util/counting.py", line 22, in nrows
    return sum(1 for _ in data(table))
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/util/counting.py", line 22, in <genexpr>
    return sum(1 for _ in data(table))
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/joins.py", line 402, in iterjoin
    lkval, lrowgrp = next(lgit)
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/sorts.py", line 303, in _iternocache
    rows = list(itertools.islice(it, 0, self.buffersize))
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/reductions.py", line 289, in itersimpleaggregate
    for k, grp in rowgroupby(table, key, value):
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/util/base.py", line 717, in <genexpr>
    return ((k.inner, vals) for (k, vals) in git)
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/util/base.py", line 701, in <genexpr>
    it = (Record(row, flds) for row in it)
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/sorts.py", line 303, in _iternocache
    rows = list(itertools.islice(it, 0, self.buffersize))
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/selects.py", line 134, in iterrowselect
    for row in it:
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/selects.py", line 133, in <genexpr>
    it = (Record(row, flds, missing=missing) for row in it)
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/basics.py", line 217, in itercutout
    for row in it:
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/basics.py", line 544, in iteraddfield
    for row in it:
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/basics.py", line 543, in <genexpr>
    it = (Record(row, flds) for row in it)
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/basics.py", line 459, in iterstack
    for row in it:
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/basics.py", line 544, in iteraddfield
    for row in it:
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/basics.py", line 543, in <genexpr>
    it = (Record(row, flds) for row in it)
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/basics.py", line 459, in iterstack
    for row in it:
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/basics.py", line 544, in iteraddfield
    for row in it:
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/basics.py", line 543, in <genexpr>
    it = (Record(row, flds) for row in it)
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/basics.py", line 459, in iterstack
    for row in it:
  File "/home/agrieco/.local/lib/python3.10/site-packages/petl/transform/basics.py", line 546, in iteraddfield
    v = value(row)
  File "/home/agrieco/johnny/johnny/sources/thinkorswim_csv/transactions.py", line 764, in _ParseDescriptionRecord
    return _ParseExpirationDescription(row.description)
  File "/home/agrieco/johnny/johnny/sources/thinkorswim_csv/transactions.py", line 912, in _ParseExpirationDescription
    assert match, description
AssertionError: REMOVAL OF OPTION DUE TO ASSIGNMENT 10.0 HUT 100 (Weeklys) 1 APR 22 6 PUT
```

**Comment by blais** [comment]
Yep, that's right. I never had any of those in my TOS account, so I haven't been able to add support for them. 
There's a type in https://github.com/edgebips/johnny/blob/master/johnny/base/transactions.md

You'd think TD/TOS would provide a spec with the full set of messages they support; alas, just getting an answer about this from them is a challenge (and the answer is "no"). Maybe a TOS developer within reads this one day and decides to spill the beans (now that would be useful). The way I went about implementing this is by downloading my own logs and figuring out *some* way to normalize the data. *urg*

Not sure what I can do. Maybe you can send me a patch?

**Comment by agrieco** [comment]
My guess is, they don't have a spec.  I keep finding differences in stuff like TOSWeb that I submitted before.  I'll clean up more of those and send them over. 

On this issue of assignment- I'd happily submit patches but to be honest and I can handle the parsing differences but I'm unclear how to make sure the transaction is appropriately captured.  It will take some time for sure.  If you had other reference functions/hints I could check out (I looked at Tastytrade parsing but it was pretty different at first glance), that would help.   Alternatively- I'm happy to provide the transactions that are generating these errors.

**Comment by blais** [comment]
Sure, send some example rows. I can't promise anything, I'm working 70 hour weeks and I have two kids, but I can timebox it maybe.
